### ISSUE TITLE
Dane - Please.

### ISSUE THREAD

**Issue by HaloFloof** [pterodactyl/whmcs#58]
I need help and youve banned me from your Discord and closing my threads on GitHub. Why dont you do me a favor? I can even pay if you want money.

**Comment by HaloFloof** [comment]
I was initially considering donating before all this happened to be honest with you

**Comment by TrixterTheTux** [comment]
The issues will continue getting closed because it isn't an issue with the module and this isn't for configuration issues. Getting banned due to your attitude isn't our fault, and instead of properly dealing with it you decided to ban evade while lying to the staff about who you actually were. Further creation of issues will lead you to get banned from the repository.
