### ISSUE TITLE
One last thing sorry for creating another issue I didnt know where else to comment or ask

### ISSUE THREAD

**Issue by HaloFloof** [pterodactyl/whmcs#59]
So where should I ask these questions? And what is the solution for the problem? Should we DM on Discord, WhatsApp, or what?

**Comment by DarthShmev** [comment]
pterodactyl.io/discord

**Comment by HaloFloof** [comment]
They banned me just because I said they should implement some billing like GameDash did. Then it escalated between me and one of the staff members just because they don't like being told another software is better than theirs. It's ok if another software is better than yours, just make yours better by seeing what do they do better. Competition in the world drove us to where we are now.

**Comment by SnowboiTheGr8** [comment]
pterodactyl, being a free open source project maintained by a community of people isn't competing with anyone in any sense of the word - the team truly couldn't give two fucks if you use it or not, they don't gain or lose anything either way

**Comment by HaloFloof** [comment]
@SnowboiTheGr8 You didnt get me. Pterodactyl is great. But ofc they want it to be better, thats why they update it. I was suggesting that they should implement billing and not have people pay for WHMCS and they got upset.

**Comment by SnowboiTheGr8** [comment]
pterodactyl isn't made for or by hosting companies, why you think they would want to work on something as behemoth as a billing system in the software is bewildering

**Comment by HaloFloof** [comment]
@SnowboiTheGr8 What is your point? If it wasnt for hosting companies why would they even make a WHMCS module? What panel do you use for Crident Networks?

**Comment by SnowboiTheGr8** [comment]
just because my car has a first aid kit doesn't meant my car is designed for first aid - the whmcs module is maintained by crident because we want people to test it, and we want to give back to the project a bit, if it wasn't for that there probably wouldn't be a maintained whmcs module, and just because we do that doesn't mean pterodactyl is designed for hosting companies or care about your hosting company using it

**Comment by HaloFloof** [comment]
So you use WHMCS and Pterodactyl, even though its not for hosting companies you say? I dont understand what youre trying to say.

**Comment by SnowboiTheGr8** [comment]
> 
> So you use WHMCS and Pterodactyl, even though its not for hosting companies

correct

**Comment by HaloFloof** [comment]
Then why are you asking me not to use it?

**Comment by DarthShmev** [comment]
Stop.

**Comment by SnowboiTheGr8** [comment]
i never asked you not to use it, i just said no one cares if you use it or not

**Comment by HaloFloof** [comment]
You arent answering the question that I opened this thread for what are you on about?

**Comment by SnowboiTheGr8** [comment]
because your question was already answered, and clearly someone needs to make it obvious to you that you blew your chance in the discord, got banned, so you're on your own & no one owes you anything

**Comment by DaneEveritt** [comment]
I'm not sure why you expect any of us to suddenly want to help you not only because you continue spamming Github, creating alts to bypass bans, and let us not forget how you acted previously.

https://github.com/pterodactyl/panel/blob/develop/CODE_OF_CONDUCT.md

"Trolling, insulting/derogatory comments, and personal or political attacks" are unacceptable behavior in our community per the code of conduct. Please re-evaluate how you act online in the future if you do not want to deal with the consequences. Thanks. 

![](http://kelp.in/RgyB5n.png)

![](http://kelp.in/fJGHvC.png)
